Cd:
- 0.02
- 0.02
- 0.03
Cl:
- 0.2
- 0.2
- 0.2
ThrusterPos1:
- -6
- 0
- 3.5
ThrusterPos2:
- -6
- -3.03
- -1.75
ThrusterPos3:
- -6
- 3.03
- -1.75
action_filter: 0.5
airship_PATH: NMPC_airship//RL/airship_model//urdf//airship.urdf
angvelrand:
- -0.2
- 0.2
buoyancy_gain: 5000
diameter: 8
f: 0.004166666666666667
g: -9.81
length: 16
linvelrand:
- -1
- 1
mass: 474.181
no_thrusters: 3
orirand:
- -0.2
- 0.2
plane_PATH: plane.urdf
posrand:
- -1
- 1
reward_coeff:
- 10
- 10
- 0
- 50
- 1
rho: 0.089
startOri:
- 0
- 0
- 0
startPos:
- 0
- 0
- 100
target_PATH: NMPC_airship//RL//airship_model//urdf//target.urdf
target_range:
- - 100
  - 100
- 200
thrust: 10000
thrust_gain: 2000
